env:
  global:
  # Docker Repository
  - REPO=fjudith/limesurvey
  # Compute docker tag
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - FPM_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "fpm"; else echo $TRAVIS_BRANCH-fpm ; fi`
  
sudo: required
services:
  - docker

jobs:
  include:
  - stage: Build
    env:
      - BASE_IMAGE=apache
      - HTTP_PORT=50080
    script:
      - pushd  ${BASE_IMAGE}/
      - docker-compose up -d
      - sleep 10
      - docker logs limesurvey
      - curl -i http://localhost:${HTTP_PORT}
    after_success: 
      - if [[ $TRAVIS_PULL_REQUEST != "false" ]; then
          echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin;
          docker tag ${REPO}:latest ${REPO}:${TAG};
          docker push ${REPO}:${TAG};
        fi
  - stage: Build
    env:
      - BASE_IMAGE=fpm
      - HTTP_PORT=58080
    script:
      - pushd  ${BASE_IMAGE}/
      - docker-compose up -d
      - sleep 10
      - docker logs limesurvey
      - docker logs nginx
      - curl -i http://localhost:${HTTP_PORT}
    after_success: 
      - if [[ $TRAVIS_PULL_REQUEST != "false" ]; then
          echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin;
          docker tag ${REPO}:fpm ${REPO}:${FPM_TAG};
          docker push ${REPO}:${FPM_TAG};
          docker push ${REPO}:nginx;
        fi
