version: '3.7'

services:
  mariadb:
    image: amd64/mariadb:10.5
    container_name: mariadb
    hostname: mariadb
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: limesurvey
      MYSQL_ROOT_PASSWORD: V3rY1ns3cur3P4ssw0rd
      MYSQL_USER: limesurvey
      MYSQL_PASSWORD: V3rY1ns3cur3P4ssw0rd
    volumes:
      - limesurvey-db:/var/lib/mysql

  memcached:
    image: memcached
    container_name: memcached
    hostname: memcached
    expose:
      - 11211

  limesurvey:
    build:
      context: ./
    image: fjudith/limesurvey:fpm
    restart: always
    container_name: limesurvey
    hostname: limesurvey
    environment:
      MEMCACHED_HOST: memcached
      PUBLIC_URL: http://survey.example.loc
      SMTP_HOST: smtp.example.com
      SMTP_TLS: "on"
      SMTP_PORT: 465
      SMTP_AUTH: "off"
      MAIL_FROM_DEFAULT: no-reply@example.com
      MAIL_DOMAIN: mail.example.com
    expose:
      - 9000
    volumes:
      - limesurvey-upload:/var/www/html:rw
    depends_on:
      - mariadb
      - memcached

  nginx:
    image: fjudith/limesurvey:nginx
    container_name: nginx
    hostname: nginx
    ports:
      - 8080
    volumes:
      - limesurvey-upload:/var/www/html:rw
    depends_on:
      - memcached
      - limesurvey

volumes:
  limesurvey-db:
  limesurvey-upload:
  limesurvey-data:
    